import { Activity, Customer, Deal, Task } from "./types";

export const customers: Customer[] = [
  {
    id: "cus-aurora",
    company: "Aurora Legal Group",
    contactName: "Elena Park",
    email: "elena@auroralegal.example",
    segment: "Agency",
    status: "Proposal",
    value: 18600,
    probability: 68,
    owner: "Ji",
    lastTouch: "Today",
    nextStep: "Send revised automation scope",
    health: "Healthy",
  },
  {
    id: "cus-northstar",
    company: "Northstar Clinics",
    contactName: "David Chen",
    email: "david@northstar.example",
    segment: "Healthcare",
    status: "Qualified",
    value: 12400,
    probability: 54,
    owner: "Maya",
    lastTouch: "Yesterday",
    nextStep: "Book data privacy review",
    health: "Needs Follow-up",
  },
  {
    id: "cus-summit",
    company: "Summit Supply Co.",
    contactName: "Rachel Moore",
    email: "rachel@summitsupply.example",
    segment: "Manufacturing",
    status: "Won",
    value: 24400,
    probability: 100,
    owner: "Ji",
    lastTouch: "May 22",
    nextStep: "Schedule onboarding handoff",
    health: "Healthy",
  },
  {
    id: "cus-brightpath",
    company: "BrightPath Learning",
    contactName: "Amir Wilson",
    email: "amir@brightpath.example",
    segment: "Education",
    status: "Lead",
    value: 7200,
    probability: 31,
    owner: "Noah",
    lastTouch: "May 21",
    nextStep: "Qualify budget and timeline",
    health: "Healthy",
  },
  {
    id: "cus-cobalt",
    company: "Cobalt Metrics",
    contactName: "Sophia Bennett",
    email: "sophia@cobalt.example",
    segment: "SaaS",
    status: "At Risk",
    value: 15800,
    probability: 42,
    owner: "Avery",
    lastTouch: "May 18",
    nextStep: "Escalate integration blocker",
    health: "Blocked",
  },
  {
    id: "cus-lumen",
    company: "Lumen Retail Ops",
    contactName: "Marcus Hall",
    email: "marcus@lumenops.example",
    segment: "SaaS",
    status: "Qualified",
    value: 9100,
    probability: 49,
    owner: "Maya",
    lastTouch: "May 17",
    nextStep: "Share dashboard prototype",
    health: "Needs Follow-up",
  },
];

export const deals: Deal[] = [
  {
    id: "deal-1",
    customerId: "cus-aurora",
    title: "Client intake automation",
    stage: "Proposal",
    amount: 18600,
    closeDate: "Jun 12",
  },
  {
    id: "deal-2",
    customerId: "cus-northstar",
    title: "Patient document workflow",
    stage: "Qualified",
    amount: 12400,
    closeDate: "Jun 20",
  },
  {
    id: "deal-3",
    customerId: "cus-summit",
    title: "Supplier portal MVP",
    stage: "Won",
    amount: 24400,
    closeDate: "May 30",
  },
  {
    id: "deal-4",
    customerId: "cus-brightpath",
    title: "Lead scoring dashboard",
    stage: "Lead",
    amount: 7200,
    closeDate: "Jul 2",
  },
  {
    id: "deal-5",
    customerId: "cus-cobalt",
    title: "CRM API middleware",
    stage: "At Risk",
    amount: 15800,
    closeDate: "Jun 8",
  },
  {
    id: "deal-6",
    customerId: "cus-lumen",
    title: "Operations reporting tool",
    stage: "Qualified",
    amount: 9100,
    closeDate: "Jun 25",
  },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    customerId: "cus-aurora",
    title: "Update proposal with API timeline",
    owner: "Ji",
    priority: "High",
    status: "Open",
    dueDate: "Today",
  },
  {
    id: "task-2",
    customerId: "cus-northstar",
    title: "Prepare compliance checklist",
    owner: "Maya",
    priority: "High",
    status: "In Progress",
    dueDate: "Tomorrow",
  },
  {
    id: "task-3",
    customerId: "cus-summit",
    title: "Create onboarding workspace",
    owner: "Ji",
    priority: "Medium",
    status: "Open",
    dueDate: "May 26",
  },
  {
    id: "task-4",
    customerId: "cus-cobalt",
    title: "Review failed webhook payloads",
    owner: "Avery",
    priority: "High",
    status: "Open",
    dueDate: "Today",
  },
  {
    id: "task-5",
    customerId: "cus-lumen",
    title: "Send dashboard screenshots",
    owner: "Maya",
    priority: "Low",
    status: "Done",
    dueDate: "May 22",
  },
];

export const activities: Activity[] = [
  {
    id: "act-1",
    customerId: "cus-aurora",
    type: "Email",
    title: "Proposal revision requested",
    detail: "Client asked for clearer milestone breakdown and post-launch support terms.",
    createdAt: "Today 10:42",
  },
  {
    id: "act-2",
    customerId: "cus-aurora",
    type: "Meeting",
    title: "Discovery call completed",
    detail: "Mapped client intake flow, document review steps, and CRM routing requirements.",
    createdAt: "Yesterday 15:20",
  },
  {
    id: "act-3",
    customerId: "cus-northstar",
    type: "Call",
    title: "Security questions raised",
    detail: "Team needs clarification on data retention, audit logs, and user permissions.",
    createdAt: "Yesterday 11:05",
  },
  {
    id: "act-4",
    customerId: "cus-summit",
    type: "System",
    title: "Deal marked as won",
    detail: "Implementation project created and onboarding task queue opened.",
    createdAt: "May 22 09:30",
  },
  {
    id: "act-5",
    customerId: "cus-cobalt",
    type: "System",
    title: "Integration failure detected",
    detail: "Webhook retries failed because destination CRM rejected a required field.",
    createdAt: "May 20 16:12",
  },
  {
    id: "act-6",
    customerId: "cus-lumen",
    type: "Note",
    title: "Stakeholder alignment",
    detail: "Operations lead wants one dashboard for revenue, order exceptions, and weekly tasks.",
    createdAt: "May 17 14:05",
  },
];
